### ISSUE TITLE
If solace queue is restarted, the consumer not reconnect

### ISSUE THREAD

**Issue by Sicmatr1x** [SolaceSamples/solace-samples-javascript#47]
After the consumer is connected to a solace queue, and the solace queue server is restarted, the consumer will disconnected to this queue forever.

This is the consumer would output.

```
=== An error happened, the message consumer is down ===
```

And you can see there will have no consumer though the queue monitor.

This was happend in **PRODUCT ENVIRONMENT**, and when I restart the progress which is consumming the msg, it reconnected again.

**Comment by Mrc0113** [comment]
Closing stale issue due to inactivity. 😴
To have this issue re-opened please add a comment below with a detailed explanation.
Thank you for your contributions ❤️

Please head over to https://solace.community for general guidance, these repos contain sample applications to quickly get started but are not meant to be production ready code. Solace Messaging APIs support error handling and connection retries strategies.
